### ISSUE TITLE
Modify the Hands text box in the weapons sheets to be able to type letters and not just number

### ISSUE THREAD

**Issue by Caius1131** [WookieeMatt/Essence20#104]
Modify the Hands text box in the weapon sheet for the purpose being able to input Versatile weapons

**Comment by phildominguez** [comment]
> Modify the Hands text box in the weapon sheet for the purpose being able to input Versatile weapons

Good catch. Should this be a dropdown? Will it always be 1, 2, or Versatile?

**Comment by Caius1131** [comment]
might be better to just turn it into a text box where you can type anything on it for case of future proofing. Weapons can vary from 1-6 hand or versatile so far
