### ISSUE TITLE
SPT not refreshing on CLient side

### ISSUE THREAD

**Issue by guswadsworth12** [WookieeMatt/Essence20#123]
SPT does not update on client side automatically.

Toggling the SPT on the client side will update it

refreshing page also works
![vivaldi_rNf3MwS0Qs](https://user-images.githubusercontent.com/28365506/184647774-d63f2097-399c-4368-aaab-b2e12cfdf817.gif)
![vivaldi_AMKRUPWkLv](https://user-images.githubusercontent.com/28365506/184647929-f17b92c5-fd17-44ee-b3e9-bc683877239a.gif)

**Comment by phildominguez** [comment]
Looks like we might be able to use sockets to tell the player clients to game.StoryPointsTracker.render() https://foundryvtt.wiki/en/development/api/sockets
