### ISSUE TITLE
Willpower and Cleverness Swap

### ISSUE THREAD

**Issue by VtGears** [WookieeMatt/Essence20#140]
The Unmorphed Willpower and Cleverness have swapped essence values with each other.
To recreate just type in any number value in smarts and social.
![Screenshot 2022-08-20 144358](https://user-images.githubusercontent.com/111663513/185766991-93770e9c-21b5-43f8-bbc5-0fc114a7b950.png)
![Screenshot 2022-08-20 144250](https://user-images.githubusercontent.com/111663513/185766995-d2e5fd17-a84a-4350-b46a-d67cc3c01649.png)

**Comment by phildominguez** [comment]
Thanks for finding this! PR is up for a fix.
