### ISSUE TITLE
Skill Selection Missing

### ISSUE THREAD

**Issue by VtGears** [WookieeMatt/Essence20#144]
When making a weapon the targeting skill is missing from the choices listed.
![Screenshot 2022-08-21 162109](https://user-images.githubusercontent.com/111663513/185815239-441d925c-9ce1-42f6-9112-b913d05b3473.png)

**Comment by guswadsworth12** [comment]
Good Find we'll get that fixed thank you

**Comment by phildominguez** [comment]
Looks like this was fixed here https://github.com/WookieeMatt/Essence20/pull/138

**Comment by guswadsworth12** [comment]
Sweet. Closing and marking as resolved
