### ISSUE TITLE
Armor Types

### ISSUE THREAD

**Issue by DigitalDevil21** [WookieeMatt/Essence20#145]
Lack of Ultra-Heavy Armor option for those with the correct armor training skill.
![image](https://user-images.githubusercontent.com/111718550/185827665-5a5208a0-4bac-40e4-bef6-652a1363011b.png)

![image](https://user-images.githubusercontent.com/111718550/185827824-fbde4d50-c39c-4140-bbbf-27b12d1c6748.png)

**Comment by guswadsworth12** [comment]
In beta release.
