### ISSUE TITLE
Cleverness and Willpower stats

### ISSUE THREAD

**Issue by DigitalDevil21** [WookieeMatt/Essence20#148]
Setting smarts to 3 and social to 4 decreases Willpower defense in morphed form by 1 and increases Cleverness defense by 1 when morphed
![image](https://user-images.githubusercontent.com/111718550/185829383-e07a7541-2292-4881-8420-ce5e7ad94693.png)

**Comment by guswadsworth12** [comment]
THis is fixed in next version of Beta
