### ISSUE TITLE
Origin - PC sheet

### ISSUE THREAD

**Issue by guswadsworth12** [WookieeMatt/Essence20#163]
![image](https://user-images.githubusercontent.com/28365506/186503053-7d7f90cd-93f3-483c-93bd-b4a30f2554f8.png)

Not loading Name properly. 

Lets also have it display in the same order as the item.

**Comment by phildominguez** [comment]
Something to note is that descriptions are automatically put at the bottom of an expanded item, so that would possibly need to be addressed for all items if we want it at the top of an Origin item.
