### ISSUE TITLE
Macro bar Support for Items. 

### ISSUE THREAD

**Issue by guswadsworth12** [WookieeMatt/Essence20#168]
Items not rolling from Macro Bar

**Comment by phildominguez** [comment]
I think the issue may be that you don't have an actor in the scene. It's supposed to alert you with this:
![image](https://user-images.githubusercontent.com/41161497/186785871-82ef1dfe-0fdd-42f1-9406-12f0f3dd597e.png)
but there is a typo preventing the message from popping up.
