### ISSUE TITLE
GI-Joe and Transformers

### ISSUE THREAD

**Issue by guswadsworth12** [WookieeMatt/Essence20#193]
Add in the Transformer and GI-Joe SHeets.

Differences:
The front page of the character sheet changes are really simple. 

- GI Joe loses personal power. 
- Transformers personal power becomes Energon and gains a faction choice.
- GI Joe name becomes Code Name

Backside

**Comment by phildominguez** [comment]
![image](https://user-images.githubusercontent.com/41161497/189766281-d2f32382-cd25-4b86-973d-c42414a50ae6.png)
Should we make Faction a text input? Radios? Dropdown?

**Comment by guswadsworth12** [comment]
I think that radials make sense honestly.

**Comment by guswadsworth12** [comment]
GI Joe's get a Focus (essentially a subclass) alongside their role. 
![image](https://user-images.githubusercontent.com/28365506/190206160-6a7267d3-08e9-45eb-90de-8c51c39d9ea4.png)

Training and Qualifications
![image](https://user-images.githubusercontent.com/28365506/190206306-70e8da9a-dd90-405d-b184-92524b017df4.png)

**Comment by guswadsworth12** [comment]
![image](https://user-images.githubusercontent.com/28365506/190206769-506f339e-de01-40f8-a1da-fc2f64b49811.png)
Faction and Energon

![image](https://user-images.githubusercontent.com/28365506/190206907-ab534d72-c6f0-4328-8dd4-14f196683a0c.png)
Harpoints

Alt Modes.
![image](https://user-images.githubusercontent.com/28365506/190207050-ee78f466-959f-4743-bf8e-5e8dbc845d4d.png)

**Comment by phildominguez** [comment]
@guswadsworth12 Energon is just a reskin of Personal Power, right? Which is actually just a Resource that's created by default when a PR is made, so we can just tweak that string when a Transformer is created.

**Comment by phildominguez** [comment]
![image](https://user-images.githubusercontent.com/41161497/191586058-20226343-9123-46a7-ad52-f405fd621fc2.png)
There's a bunch more going on with Hardpoints than that single field in the character sheet lets on.

**Comment by phildominguez** [comment]
I'm thinking we could use our existing Weapons section (renamed as Weapon Hardpoints, maybe) and add a Non-Weapon Hardpoints section. The only fields they need are Alt Mode, Bot Mode, and Prerequisite.

**Comment by phildominguez** [comment]
Should alt mode weapons (attacks) just be the same as normal weapons? They really simplified them on the sheet, but I'm not sure that they are any different.
