### ISSUE TITLE
Stop the skill container from collapsing after editing

### ISSUE THREAD

**Issue by phildominguez** [WookieeMatt/Essence20#310]
Making any modifications to within the collapsible skill container causes it to collapse automatically. This is very annoying when there are multiple changes that need to be made. Find a way to keep it open instead.

**Comment by guswadsworth12** [comment]
Adding documents for Research
https://stackoverflow.com/questions/59562650/how-to-prevent-search-box-from-collapsing

Suggestion from foundry server
![image](https://user-images.githubusercontent.com/28365506/228286403-244cb96b-a0ec-4da4-b170-ac1852b9525f.png)
