### ISSUE TITLE
Weapon Item Effect Changes

### ISSUE THREAD

**Issue by JFranklin3000** [WookieeMatt/Essence20#320]
Redo Weapon Item Sheet to support rolling various effects. 
Currently Effect and Alternate Effect are just text fields. 
Change so that there are fields for damage value and damage type. 
Alternate Effects would also have a radius or area option and cost for downshifts. 

![image](https://user-images.githubusercontent.com/71140111/227783718-99be5055-8e33-4b71-bd52-ed4116ed132b.png)

**Comment by phildominguez** [comment]
This may require a new item, such as Weapon Effect, which could be owned by Weapons. This way a weapon can customize however many effects/alternate effects they want, each with their own damage/type/range/cost etc.

**Comment by phildominguez** [comment]
Some upgrades add an alternate effect to a weapon:
![image](https://github.com/WookieeMatt/Essence20/assets/41161497/f16ddf10-2ebc-4f07-84fe-2fce7b2c82f6)
This means dragging an upgrade onto a weapon can also bring along another effect item.

**Comment by phildominguez** [comment]
![image](https://github.com/WookieeMatt/Essence20/assets/41161497/1ee26035-c370-4eca-a6a9-9dfb5c273cad)
Concept of having an Effects and Upgrades containers within each Weapon

Something to note, when dropping an upgrade or effect onto a character sheet, we will likely have to show a popup asking which weapon to apply it to.
