### ISSUE TITLE
Change Skills to contain their Essence instead of being contained in Essences. 

### ISSUE THREAD

**Issue by JFranklin3000** [WookieeMatt/Essence20#324]
Change Skills to be seperate from Essences. 

Skills would become system.skills.<skillname>

"athletics": {
  "essence": {
      "strength": true,
      "speed": false,
      "social": false,
      "smarts": false
  },
  "isSpecialized": false,
  "modifier": 0,
  "shift": "d20",
  "shiftDown": 0,
  "shiftUp": 0
},

This would allow for perks that make skills associate with other Essences.

**Comment by phildominguez** [comment]
`essence` could probably just be a string, such as "strength"

**Comment by JFranklin3000** [comment]
I think so, let me research to see if we ever get a case where it is more than one.

**Comment by JFranklin3000** [comment]
And I found one. 

![image](https://user-images.githubusercontent.com/71140111/227788020-79adf0fd-731f-4f8d-992e-c015d2cd8689.png)

**Comment by phildominguez** [comment]
> And I found one.
> 
> ![image](https://user-images.githubusercontent.com/71140111/227788020-79adf0fd-731f-4f8d-992e-c015d2cd8689.png)

Interesting, okay. What are the implications of this in play? Just if you get an essence increase for either strength or social you can upgrade intimidation?

**Comment by JFranklin3000** [comment]
That is the big one, As I am deep diving I might find another use for it somewhere as well.
