### ISSUE TITLE
Implement actor sheet for Pets

### ISSUE THREAD

**Issue by guswadsworth12** [WookieeMatt/Essence20#342]
need to add Pets and ally/contact functionality.

**Comment by phildominguez** [comment]
Repurposing this ticket to just be for adding the pet actor sheet

Helpful for defaults:
![image](https://user-images.githubusercontent.com/41161497/229322676-84b92459-4929-4b84-be05-6df1f567d434.png)

**Comment by JFranklin3000** [comment]
![B42D43B4-EE8C-4CBB-8252-6F54E158B078](https://user-images.githubusercontent.com/71140111/229323164-f88e189c-a830-4570-99b5-db22752ef2f2.jpeg)
![75D5FC24-38A8-46F0-895E-F96731154865](https://user-images.githubusercontent.com/71140111/229323170-5be86506-98d5-40b3-8d5c-928b2b234b09.jpeg)
![2ED8DA65-087E-458F-8712-1373E0D684C1](https://user-images.githubusercontent.com/71140111/229323177-404e80e2-f97c-4e1f-9134-364e8218398f.jpeg)
![4DB3CCC9-3440-4A98-A525-9715287E2056](https://user-images.githubusercontent.com/71140111/229323178-888fbdbf-fbdc-424f-a4e8-492da670b60e.jpeg)

**Comment by JFranklin3000** [comment]
Fields Requirements for Sheet. 
Name
Common
Movement
Skills
Attack
Perks
Power (Mini-cons only)
Upgrades (Drone Pets only)

**Comment by phildominguez** [comment]
After some discussions, the plan is to create a single Companion actor who has all the required fields/items. A selector on their sheet will let users choose between Pet, Mini-Con, Drone, and Human, which can filter what is displayed in the sheet.
