### ISSUE TITLE
Add support for Token Action HUD

### ISSUE THREAD

**Issue by JFranklin3000** [WookieeMatt/Essence20#343]
Add support for Token Action HUD see link below. 

https://github.com/Drental/fvtt-tokenactionhud/blob/master/adding_systems.md

**Comment by phildominguez** [comment]
Example PR for adding support to a system: https://github.com/Drental/fvtt-tokenactionhud/pull/209/files

**Comment by phildominguez** [comment]
We're instead going to look into TAH Core: https://github.com/Larkinabout/fvtt-token-action-hud-core

With this method we'll be making our own separate module, which will set TAH Core as a dependency.

Example modules:
- https://github.com/farling42/token-action-hud-cyphersystem/blob/master/scripts/module.js
- https://gitlab.com/vtt2/token-action-hud-opend6-space
- https://gitlab.com/vtt2/token-action-hud-ghostbusters

**Comment by phildominguez** [comment]
Repo for the module: https://github.com/phildominguez/token-action-hud-essence20
