### ISSUE TITLE
Combat Tracker No longer assignable 

### ISSUE THREAD

**Issue by guswadsworth12** [WookieeMatt/Essence20#364]
![image](https://user-images.githubusercontent.com/28365506/230271028-9a4dafaf-5b94-4500-bbbd-0d4201ff1093.png)
Above error populates when attempting to roll multiple characters using the roll all or roll npc options in the combat tracker.

**Comment by guswadsworth12** [comment]
To replicate attempt to roll or reroll initiative from the combat tracker. Test with all Sheets.  will likely throw error. Attempt to do this from token or combat tracker only.  Gif below showing issue
![Foundry_Virtual_Tabletop_2fJCFX50ot](https://user-images.githubusercontent.com/28365506/230272445-c6dbc24a-2b0e-4f4d-b5be-0a89c052537d.gif)

**Comment by guswadsworth12** [comment]
![JVrdKnUBae](https://user-images.githubusercontent.com/28365506/230272699-bbe1f73b-3106-42d8-9f94-46bef4a74248.gif)

**Comment by phildominguez** [comment]
I'm not able to replicate this. My steps:
1. Create an actor of each type
2. Drop them onto a scene
3. Add them to a new combat encounter
4. In the combat tracker, right click each of them -> Reroll Initiative
5. Initiatives all roll correctly without error
