### ISSUE TITLE
Spec Not rolling Correctly

### ISSUE THREAD

**Issue by guswadsworth12** [WookieeMatt/Essence20#38]
![image](https://user-images.githubusercontent.com/28365506/164066958-4a6f81be-75cf-4d6e-b35a-408aaf06d66b.png)

Specilization not keeping Highest Skill dice.

**Comment by phildominguez** [comment]
Ah, I misread the specialization roll rules. I'll check this out, thanks!

**Comment by guswadsworth12** [comment]
Simple fix would be to {dice}kh I checked with a manual roll this makes it roll correctly

**Comment by guswadsworth12** [comment]
Works Great Now. Keeps as intended!!!
