### ISSUE TITLE
Unable to edit Origins or create new ones with latest update

### ISSUE THREAD

**Issue by Soundwavesghost** [WookieeMatt/Essence20#393]
When I try to create or edit one of the ones in the compendium they are not able to be edited even on the character sheet. They function for the drag and drop however.

![image](https://user-images.githubusercontent.com/5963543/234393084-76227d42-3207-4816-80e8-f4a60bfc0f8e.png)

**Comment by JFranklin3000** [comment]
The error is that the Origin doesn't have a Perk attached as the Origin Benefit. Because of some work we did to force choosing the Essence and Skill it doesn't finish without one.

**Comment by Soundwavesghost** [comment]
I get the same error though when I select the imported ones.
![image](https://user-images.githubusercontent.com/5963543/234405426-6989a9cf-fcd0-453d-920e-ac8cba01700f.png)

**Comment by Soundwavesghost** [comment]
Fresh game world idn't have the error so it is a module on my install. Apologies.

**Comment by JFranklin3000** [comment]
It might be existing Compendiums that don't have an index value for some reason. We will keep looking at it just in case.

**Comment by JFranklin3000** [comment]
New version coming out with a fix for other compendiums.
