### ISSUE TITLE
Test Foundry v11

### ISSUE THREAD

**Issue by phildominguez** [WookieeMatt/Essence20#399]
Test Foundry v11 and determine if any fixes are needed

**Comment by JFranklin3000** [comment]
![image](https://user-images.githubusercontent.com/71140111/235331014-2058af6e-9be4-4604-b325-58775303df67.png)

issue with descriptions in v11

**Comment by JFranklin3000** [comment]
fix for item-sheet.mjs (might need that on Actor as well)

context.system.description = TextEditor.enrichHTML(itemData.system.description, {async: false});

**Comment by JFranklin3000** [comment]
A few fixes have already been applied for v11 support.
