### ISSUE TITLE
Power Rangers - Toughness added to Unmorphed form, And Missing Speeds

### ISSUE THREAD

**Issue by StrataArkright** [WookieeMatt/Essence20#446]
I just updated to the new release, and noticed two issues when going over my players sheets.

First problem seems to be that the armor bonuses are added to their unmorphed forms. When i click the 'Morph' button, it reduces the toughness values by the armor's designated bonus.

Second issue, Aerial/Ground/Swim speeds do not show in the Skills tab on a character that has already been set up, With an Origin already added to the sheet, and previously had the movement values manually input. Additionally, it will not allow me to enter the speed values on the Skills tab. And when adding the values to an Origin, it does not populate the movement speed on the skills tab either. The movement box will show a red line running its length.

![image](https://github.com/WookieeMatt/Essence20/assets/136207945/af8068f0-f913-4313-82fa-e868da264379)

**Comment by JFranklin3000** [comment]
The movement is being looked into we will let you know once we find the issue. 

Power Rangers according to what I was able to get from long hours of discussion don't actually wear armor. They do however get a bonus to defenses well morphed that comes first from the It's Morphin Time Perk. On that perk there are 4 disabled effects that you turn on the one that is appropriate for your character. Other Perks and abilities also add to that (system.defenses.toughness.morphed if you need to do an effect)
