### ISSUE TITLE
Weapons and Gear Item Edit and Item Delete button do not work 

### ISSUE THREAD

**Issue by WookieeMatt** [WookieeMatt/Essence20#45]
![image](https://user-images.githubusercontent.com/36809171/164533603-dbf6d0be-443b-46f4-a082-76837a8cf804.png)

**Comment by phildominguez** [comment]
Interesting, not seeing this. Are you on `main`? Does it happen if you create a fresh character?

**Comment by WookieeMatt** [comment]
i'm on Graphix but i thought they were equal. Its happening just with Weapons and Gear, Armor works as it should

**Comment by phildominguez** [comment]
https://github.com/WookieeMatt/Essence20/pull/46
