### ISSUE TITLE
New Weapon Layout 4.0

### ISSUE THREAD

**Issue by StrataArkright** [WookieeMatt/Essence20#519]
With the new weapon lay out, with individual effect rolls, They do not currently roll linked to the weapon itself when you roll an attack. They only roll the skill test. Additionally, any rolls that utilize personal power no longer automatically subtract from the pool on the sheet.

Snapshots of two different "Blade Blaster" Attacks. One prior to update, one after. Both rolled from their entries on the Combat tab, and under the Weapon(Old)/Weapon Effect(New)

![image](https://github.com/WookieeMatt/Essence20/assets/136207945/1111b493-4296-4018-b9e3-238347f0af28)
![image](https://github.com/WookieeMatt/Essence20/assets/136207945/3659e782-9ab9-468d-b21a-19b51df6f122)

**Comment by JFranklin3000** [comment]
This has been fixed in the 4.1.0 release.
