### ISSUE TITLE
Improve chat cards for weapon effect rolls

### ISSUE THREAD

**Issue by phildominguez** [WookieeMatt/Essence20#520]
Addresses https://github.com/WookieeMatt/Essence20/issues/519

Currently, the chat cards for weapon effects only mention the skill being used and whether a snag/edge applies:
![image](https://github.com/WookieeMatt/Essence20/assets/41161497/67962ca0-2ef5-4b2b-a94f-5e6e5910d460)
At _minimum_ we should include the weapon and effect names being used. An example would be something like the magic bauble card:
![image](https://github.com/WookieeMatt/Essence20/assets/41161497/8250bc69-800d-432c-aa76-68f034315f8d)

However, I think it's possible to render the full template (like when you click the info button). You can see an example of that being coded [here](https://www.youtube.com/watch?v=RwbzucCs4Dw&list=PLFV9z59nkHDccUbRXVt623UdloPTclIrz&index=6&t=736s) in the `DeathCheck()` method being written.

Also, I noticed that in our [switch statement](https://github.com/WookieeMatt/Essence20/blob/main/module/dice.mjs#L97) for handling types of skill rolls we have a case for `weapon`, which is supposed to be `weaponEffect` now.

**Comment by JFranklin3000** [comment]
We should add the weapon traits to this dialog as well.
