### ISSUE TITLE
Wealth die and money, tracking

### ISSUE THREAD

**Issue by Ryanthebadass** [WookieeMatt/Essence20#538]
I would like a section of the sheet for tracking a players wealth dice and for campaigns like mine, a way of tracking a money number other than just putting in a notes thank you

**Comment by techogre** [comment]
Agreed. A tracking of the Wealth "skill" would be very useful.

**Comment by JFranklin3000** [comment]
Wealth Die will be in next release, for actually tracking wealth I would do that in the notes.
