### ISSUE TITLE
Roles missing for My Little Pony.

### ISSUE THREAD

**Issue by techogre** [WookieeMatt/Essence20#549]
I noticed the Roles for the MLP game are missing. I understand if the Essence increases are not included, but the Role Perks should be included.

Thanks!

**Comment by techogre** [comment]
See [https://github.com/WookieeMatt/Essence20/issues/550](url) for a possible solution to the Essence increase problem.

**Comment by JFranklin3000** [comment]
Roles are next on the list as we continue to work through the system.

**Comment by JFranklin3000** [comment]
Roles will be released in 4.2
