### ISSUE TITLE
Essence ranks are missing for My Little Pony

### ISSUE THREAD

**Issue by techogre** [WookieeMatt/Essence20#550]
There is no spot to indicate the ranking of Essence (Dimond, Gold, Silver, Bronze). Could be used when fixing Roles.

Thanks!

**Comment by JFranklin3000** [comment]
As part of rolling out Roles, the intention is to include that option.

**Comment by JFranklin3000** [comment]
![image](https://github.com/WookieeMatt/Essence20/assets/71140111/bfe371e0-19fb-497d-8606-16a0ecaf327c)
How about this?

**Comment by JFranklin3000** [comment]
This is in beta. Will be released in 4.2
