### ISSUE TITLE
Label for Story Points need a Friendship Points option

### ISSUE THREAD

**Issue by techogre** [WookieeMatt/Essence20#551]
In the setup, there should be an option for "Friendship Points" and "Story Points". Currently, there are only "Story Points".

Thanks!

**Comment by JFranklin3000** [comment]
That is in the Essence20 Game Settings. 
![image](https://github.com/WookieeMatt/Essence20/assets/71140111/6d10d451-9813-4e5e-9417-9004faecdfc4)
