### ISSUE TITLE
Casting a spell does not increase the extra Down Shift on the spell casting skill in MLP

### ISSUE THREAD

**Issue by techogre** [WookieeMatt/Essence20#552]
When a character casts a Spell in Combat, the Spellcasting Skill should be lowered by 1 level (effectively adding 1 Shift Down after they cast a spell) At the end of any turn they did not cast a spell, the Down Shifts from spell casting is reduced by 1.

Expected behaviour:

Turn 1 - Elusive the Unicorn casts Energy Beam. The cost is 1. It has a total of 1 extra Down Shift on the next casting.
Turn 2 - Elusive the Unicorn casts Energy Beam. The cost is 2. It has a total of 2 extra Down Shift on the next casting.
Turn 3 - Elusive the Unicorn casts Energy Beam. The cost is 3. It has a total of 3 extra Down Shift on the next casting.
Turn 4 - Elusive the Unicorn does not cast a spell. It has a total of 2 extra Down Shift on the next casting.
Turn 5 - Elusive the Unicorn casts Energy Beam. The cost is 3. It has a total of 3 extra Down Shift on the next casting.
Turn 6 - Elusive the Unicorn does not cast a spell. It has a total of 2 extra Down Shift on the next casting.
Turn 7 - Elusive the Unicorn does not cast a spell. It has a total of 1 extra Down Shift on the next casting.
Turn 8 - Elusive the Unicorn does not cast a spell. It has a total of 0 extra Down Shift on the next casting.
Turn 9 - Elusive the Unicorn casts Energy Beam. The cost is 1. It has a total of 1 extra Down Shift on the next casting.
etc

What actually happens:

Turn 1 - Elusive the Unicorn casts Energy Beam. The cost is 1. It has a total of 1 Down Shift.
Turn 2 - Elusive the Unicorn casts Energy beam. The cost is still 1.
etc

**Comment by JFranklin3000** [comment]
Closing as duplicate see issue below. 

https://github.com/WookieeMatt/Essence20/issues/302
