### ISSUE TITLE
Scenes don't get past 90% loaded

### ISSUE THREAD

**Issue by MattBridger777** [WookieeMatt/Essence20#563]
![screenshot](https://github.com/WookieeMatt/Essence20/assets/92942471/d22333f9-90bb-4aca-9568-3330a90c282e)

Any Scene created does not get past 90% loaded. 

Using Foundry v11 b315 on Forge.
Essence20 4.1.2

Newly installed. No modules active. 
Console reports no Errors. Console warnings all appear to revolve around "downloadable font: Glyph bbox was incorrect" and "WebGL context was lost."

**Comment by phildominguez** [comment]
Any issues with other systems? My gut tells me it's a Foundry issue. It's odd that you're getting `undefined` values in your story points tracker, almost like the settings for the system are not being initialized. It should be pulling those values from here:
![image](https://github.com/WookieeMatt/Essence20/assets/41161497/66167f6c-2219-42b6-aad4-279bd395a670)

**Comment by phildominguez** [comment]
Are you using Chrome or a Chromium-based browser? Foundry [recommends it](https://foundryvtt.com/article/requirements/#:~:text=Chrome%20or%20a%20Chromium%2Dbased%20browser) and we've seen issues with players trying to use Firefox and whatnot.

**Comment by MattBridger777** [comment]
I do use Firefox.
Plus I installed the Foundry app on my PC instead of running it through Forge and it appears to work. It certainly doesn't display the same inability to load past 90%.

**Comment by phildominguez** [comment]
Yep, we've heard others with similar Firefox issues. Glad it's working on the client though!
