### ISSUE TITLE
there does not appear to be any roles or ways to add roles

### ISSUE THREAD

**Issue by jimthegray** [WookieeMatt/Essence20#579]
there does not appear to be any roles or ways to add roles

**Comment by phildominguez** [comment]
Currently "Role" is just a textbox in the actor's header, but our current focus is adding full `Role` items that can be dragged onto actor sheets and automate leveling. We're making good progress, but still have a bit of work to do. If you want to stay up to date on its status, your best bet is joining our [Discord](https://discord.gg/74QYVA355W). Hope this helps!
