### ISSUE TITLE
Suggestion: Unmorphed and Morphed token and sheet arts

### ISSUE THREAD

**Issue by WanderSiqueira** [WookieeMatt/Essence20#707]
I don't know if this feature already exists and I'm just dumb enough to not notice it, but it would be cool if we could change the token and sheet arts when we morph/transform or do anything alike. Thanks in advance!

**Comment by JFranklin3000** [comment]
It would be a pretty tricky thing to do in the base system, but there is a macro for this available in the #scripts channel of our Discord.

**Comment by phildominguez** [comment]
I've added [an entry to our FAQ](https://github.com/WookieeMatt/Essence20/wiki/Essence20-on-Foundry-VTT-FAQ#how-can-i-make-a-token-change-its-image-on-the-fly-for-morphingtransforming) for doing macro-based token image swapping. Reach out to us on the Discord if you run into any issues.
