### ISSUE TITLE
Perk Item not Droppable on Perk Tab

### ISSUE THREAD

**Issue by guswadsworth12** [WookieeMatt/Essence20#76]
You cannot drop a created perk from either the compendium or item tab onto a character sheet.
![vivaldi_G1R6iiNpCD](https://user-images.githubusercontent.com/28365506/179051911-e190247b-9d1e-4ce1-9094-492f9201e2a3.gif)

**Comment by phildominguez** [comment]
This is currently working for me. Are you dragging a `Perk` (from an Influence) instead of a `General Perk`?

**Comment by phildominguez** [comment]
We should probably change the tab name:
![image](https://user-images.githubusercontent.com/41161497/179400245-8746431c-a781-4457-aad6-dec714bef2b4.png)
I think we can get rid of the `Perks` header, too, since the tab only holds one thing.

**Comment by phildominguez** [comment]
We decided get rid of background perks and just use general perks for those. `generalPerks` can be renamed to just `perks`.
