### ISSUE TITLE
Weapon rolls not templated

### ISSUE THREAD

**Issue by guswadsworth12** [WookieeMatt/Essence20#78]
![Foundry_Virtual_Tabletop_gCpyqprJT3](https://user-images.githubusercontent.com/28365506/179269689-33e16ced-28fe-48a8-93d0-8a3650bbcf51.gif)

As you can see in the gif the weapon rolls just a straight might, or whatever is selected, roll. These should roll in a way thats clear that an attack is being made. Also these should be assignable as macros to the bar. But when i drag it i get a not owned error like so.

![Foundry_Virtual_Tabletop_egrRivoVZS](https://user-images.githubusercontent.com/28365506/179270579-24cea2a8-50af-46cc-8c42-f3ae715849c4.gif)

**Comment by phildominguez** [comment]
Made a separate issue for the macro error: https://github.com/WookieeMatt/Essence20/issues/81
